### PR TITLE
Added ppm and time delta widgets

### PR DESCRIPTION
**Pull request by Ankur-AVP-Patel**

### CODE REVIEW

**Comment by bobturneruk** [comment]
@Ankur-AVP-Patel  - please clear outputs and save again.

https://zhauniarovich.com/post/2020/2020-06-clearing-jupyter-output/#:~:text=When%20you%20have%20Jupyter%20notebook,Output%20%2D%3E%20Clear%20menu%20item.

**Comment by bobturneruk** [comment]
I think there's some commas missing around here:
```
# Set time delta for in source clean up
time_delta = widgets.BoundedFloatText(
    value=0.5,
    min=0,
    max=100,
    step=0.01
    description='Set time delta value'
    disabled = False
)
```

**Comment by bobturneruk** [comment]
I'm going to go ahead and work on this branch and try and fix it up.

**Review by bobturneruk — APPROVED** [review]
As usual, I rely on others to manually validate the scientific accuracy of the output. This is otherwise ready to merge. Good work @Ankur-AVP-Patel!

**Comment by Ankur-AVP-Patel** [comment]
My arch nemesis strikes again! You win this time comma's but one day, I will have the last laugh.

**Pull request merged**
