### PR TITLE
feature(smithereens): Mass Builder for PGFinder 2.0

### PR DESCRIPTION
**Pull request by ns-rse**
Much head scratching, reading, learning, trying to document how things hang together and assistance from @TheLostLambda has led to a new component that uses static Rust copmiled to WebAassembly from [Smithereens]() which takes a list of muropeptides and calculates the masses. The building blocks (currently only _E. coli_) are not actually used, as the masses of the components are internal to Smithereens.

+ All available species are duplicates (they just have different species/file names).
+ The building block components are not used, these come directly from smithereens I believe.
+ Defaults to `muropeptides_masses.csv` as output filename.
+ Lots of `console.log()` still in place.
+ Lints some files but doesn't address all errors.

Also did some minor cleaning

+ Update ruff and eslint pre-commit hooks
+ Update pyproject.toml in light of ruff config changes
+ Lint test_internal.py
+ Adds basic eslint.config.mjs and removes options from .pre-commit-configy.yaml

## ToDo

There is no doubt more than the following to do but here are a few things that can be done in the future.

+ As we are now loading the building blocks and muropeptide lists directly from the web-server/host it would perhaps make sense to do the same for the mass databases too as it is considerably faster than waiting for the Python packages to install and make these available.
+ Address the linting errors, currently a number of files are ignored via the `--no-warn-ignored` flag in `.pre-commit-config.yaml` but this should be removed and all errors addressed

### CODE REVIEW

**Comment by ns-rse** [comment]
I spent a little time looking at this and the `playrwright` tests are failing because the test that tries to click click on a plain `textbox` and so its picking up the box that runs the newer Smithereens component rather than the existing functionality.

I've been having a tinker to see if I can apply `.filter({ hasText: `Byos` })` to narrow this down but without success yet.

I'll try and find a little time to look at this over the coming weeks and am also mindful that we should probably add to the `playrwight` tests functionality that checks the new addition.

**Comment by ns-rse** [comment]
I've fixed the end-to-end tests which now pass by adding labels to each relevant section via `data-testid` and explicitly referring to these in the `web/tests/*.ts` files.

The GUI tests fail for a few reasons (see full log [here](https://github.com/Mesnage-Org/pgfinder/actions/runs/9550651384/job/26323110340?pr=285))...

1. `pnpm check --tsconfig ./tsconfig.json` tries to check all the files under `src/smithereens/pkg/` and has a lot of complaints about `smithereens_bg.js`.
2. There are some errors in the types used in `src/lib/smithereens.ts` (`arrayToConvert` type is implicitly `any` in `smithereens.ts`).
3. A complaint about `ModalSettings` in `+page.svelte`.
4. Two identical problems with trying to use `VirtFile | undefined` in `+page.svelte`.
5. Wrong export type in `FragmentsSelector.svelte`

I also have some `eslint` errors thrown by `pre-commit`, but upgrading to `estlint-9.5.0` has broken things even more and these don't show in [the CI log](https://results.pre-commit.ci/run/github/282892807/1718638916.Q36dA6l_SDGkJKPWXPIhKw).

Still to do would be to write tests that check smithereens runs correctly, but if you have any ideas or can suggest how to fix these please @TheLostLambda I would be very grateful.

**Comment by TheLostLambda** [comment]
@ns-rse Out of time for now... Pre-commit continues to be an inexplicable pain. How would you feel about dropping ESLint from it?

As long as we run prettier and svelte-check in the CI, I think that's fine? Calling `svelte-check` / `pnpm check` runs ESLint already, I'm pretty sure?

The remaining errors I can take another look at if needed, but for me `pnpm check` is showing:

```
/home/tll/Documents/University/PhD/Chapters/The Automation of LC-MS Peptidoglycan Analysis/pgfinder/web/src/lib/smithereens.ts:8:54
Error: Cannot find module 'smithereens' or its corresponding type declarations. 
import { onMount } from "svelte";
import init, { Peptidoglycan, pg_to_fragments } from "smithereens";



/home/tll/Documents/University/PhD/Chapters/The Automation of LC-MS Peptidoglycan Analysis/pgfinder/web/src/lib/smithereens.ts:85:7
Error: Element implicitly has an 'any' type because expression of type 'string' can't be used to index type '{}'.
  No index signature with a parameter of type 'string' was found on type '{}'. 
      // Save mass to dictionary
      muropeptidesMasses[muropeptide] = mass;
    }


/home/tll/Documents/University/PhD/Chapters/The Automation of LC-MS Peptidoglycan Analysis/pgfinder/web/src/lib/smithereens.ts:92:16
Error: Parameter 'arrayToConvert' implicitly has an 'any' type. 
  // Convert to CSV
  function CSV(arrayToConvert) {
    // Convert Object to Array first


/home/tll/Documents/University/PhD/Chapters/The Automation of LC-MS Peptidoglycan Analysis/pgfinder/web/src/routes/+page.svelte:39:56
Error: Cannot find module 'smithereens' or its corresponding type declarations. (ts)
  import { defaultPyio, defaultSmithereens } from "$lib/constants";
  import init, { Peptidoglycan, pg_to_fragments } from "smithereens";
```

1. Not sure about this... Could just be that we need to make it `"$lib/smithereens.ts"` or similar since it's not actually a separate module / package?
2. Need to look into how to properly express dictionary types in TS maybe?
3. This just needs a type annotation, which should be easy enough hopefully...
4. Same as 1

Let me know if you want me to take another swing at things / if I've answered all of your questions!

**Comment by ns-rse** [comment]
Thanks @TheLostLambda and no need to apologise for taking holidays at all.

Thanks for the work/commits, I wondered why my `exclude` wasn't being respected.

I'd clocked the lack of ability to import `smithereens` but was unsure where to move it to (this will also get rid of the warnings in the end-to-end tests). I'll have a tinker with the suggestion and see if it works and try addressing the other things hopefully this week but spent longer than I'd planned to fixing the end-to-end tests and adding `data-testid` to sections.

No problem removing `eslint` from `pre-commit` at all, especially if its already covered from other angles.

**Comment by ns-rse** [comment]
Wow, you've been exceptionally busy @TheLostLambda looking really good though.

**Comment by TheLostLambda** [comment]
@ns-rse  and @smesnage This is feature complete now — it still needs some documentation for the new features and I need to do something about tests... If we're not writing new ones, we should at least get the ones that already exist working!

Ready for code-review (it's hopefully not too much of a disaster) by @ns-rse if you have the time, and any answers to your questions would make for good developer documentation!

For @smesnage , I'll pester you tomorrow and we can get started on the user-facing documentation!

**Comment by TheLostLambda** [comment]
For @smesnage , the `pgfinder-next` / `smithereens` repository is now a submodule of this one, so we can have all of the code in a single link for the paper!

For @ns-rse , if you have a moment, it would be great if you could test that the installation / Rust building -> WebUI steps I added in the `smithereens.md` file work for you! Though it's not part of the automated build process yet, it's not at least something you can build from source and it all lives in this repo!

**Comment by ns-rse** [comment]
Had a go at working through the instructions.

## Building the Package

This fails for native compilation.

```bash
git submodule update --init --recursive
cd smithereens
cargo build
    Updating crates.io index
    Updating git repository `https://github.com/TheLostLambda/miette`
    Updating git repository `https://github.com/TheLostLambda/knuffel.git`
  Downloaded addr2line v0.22.0
  Downloaded convert_case v0.6.0
  Downloaded bitflags v2.6.0
  Downloaded cfg_aliases v0.2.1
  Downloaded autocfg v1.3.0
  Downloaded heck v0.5.0
  Downloaded thiserror-impl v1.0.63
  Downloaded errno v0.3.9
  Downloaded toml_datetime v0.6.6
  Downloaded utf8parse v0.2.2
  Downloaded unicode-xid v0.2.4
  Downloaded thiserror v1.0.63
  Downloaded either v1.13.0
  Downloaded bytes v1.6.1
  Downloaded borsh-derive v1.5.1
  Downloaded getrandom v0.2.15
  Downloaded quote v1.0.36
  Downloaded itoa v1.0.11
  Downloaded rustc-demangle v0.1.24
  Downloaded serde_derive v1.0.204
  Downloaded tinyvec v1.8.0
  Downloaded uuid v1.10.0
  Downloaded derive_more v1.0.0-beta.6
  Downloaded indexmap v2.2.6
  Downloaded derive_more-impl v1.0.0-beta.6
  Downloaded backtrace v0.3.73
  Downloaded allocator-api2 v0.2.18
  Downloaded serde v1.0.204
  Downloaded cc v1.1.6
  Downloaded base64 v0.22.1
  Downloaded borsh v1.5.1
  Downloaded ryu v1.0.18
  Downloaded proc-macro2 v1.0.86
  Downloaded num-traits v0.2.19
  Downloaded memchr v2.7.4
  Downloaded miniz_oxide v0.7.4
  Downloaded log v0.4.22
  Downloaded hashbrown v0.14.5
  Downloaded serde_json v1.0.120
  Downloaded zerocopy v0.7.35
  Downloaded itertools v0.13.0
  Downloaded syn v2.0.72
  Downloaded gimli v0.29.0
  Downloaded object v0.36.1
  Downloaded unicode-width v0.1.13
  Downloaded libc v0.2.155
  Downloaded linux-raw-sys v0.4.14
  Downloaded 47 crates (6.1 MB) in 0.73s (largest was `linux-raw-sys` at 1.8 MB)
   Compiling proc-macro2 v1.0.86
   Compiling unicode-ident v1.0.12
   Compiling version_check v0.9.4
   Compiling libc v0.2.155
   Compiling cfg-if v1.0.0
   Compiling memchr v2.7.4
   Compiling rustix v0.38.34
   Compiling bitflags v2.6.0
   Compiling cc v1.1.6
   Compiling linux-raw-sys v0.4.14
   Compiling gimli v0.29.0
   Compiling adler v1.0.2
   Compiling unicode-width v0.1.13
   Compiling once_cell v1.19.0
   Compiling thiserror v1.0.63
   Compiling rustc-demangle v0.1.24
   Compiling syn v1.0.109
   Compiling miniz_oxide v0.7.4
   Compiling zerocopy v0.7.35
   Compiling autocfg v1.3.0
   Compiling is_ci v1.2.0
   Compiling smawk v0.3.2
   Compiling unicode-linebreak v0.1.5
   Compiling unicode-segmentation v1.11.0
   Compiling ahash v0.8.11
   Compiling proc-macro-error-attr v1.0.4
   Compiling proc-macro-error v1.0.4
   Compiling supports-color v3.0.0
   Compiling supports-hyperlinks v3.0.0
   Compiling object v0.36.1
   Compiling num-traits v0.2.19
   Compiling textwrap v0.16.1
   Compiling supports-unicode v3.0.0
   Compiling serde v1.0.204
   Compiling owo-colors v4.0.0
   Compiling allocator-api2 v0.2.18
   Compiling heck v0.5.0
   Compiling convert_case v0.6.0
   Compiling minimal-lexical v0.2.1
   Compiling unicode-xid v0.2.4
   Compiling quote v1.0.36
   Compiling rust_decimal v1.35.0
   Compiling arrayvec v0.7.4
   Compiling nom v7.1.3
   Compiling syn v2.0.72
   Compiling base64 v0.22.1
   Compiling cfg_aliases v0.1.1
   Compiling either v1.13.0
   Compiling nix v0.28.0
   Compiling static_assertions v1.1.0
   Compiling smallvec v1.13.2
   Compiling itertools v0.13.0
   Compiling nibble_vec v0.1.0
   Compiling endian-type v0.1.2
   Compiling log v0.4.22
   Compiling home v0.5.9
   Compiling radix_trie v0.2.1
   Compiling utf8parse v0.2.2
   Compiling getrandom v0.2.15
   Compiling backtrace v0.3.73
   Compiling hashbrown v0.14.5
   Compiling addr2line v0.22.0
   Compiling chumsky v0.9.3
   Compiling terminal_size v0.3.0
   Compiling fd-lock v4.0.2
   Compiling rustyline v14.0.0
   Compiling thiserror-impl v1.0.63
   Compiling miette-derive v7.2.0 (https://github.com/TheLostLambda/miette#5b3eeba9)
   Compiling serde_derive v1.0.204
   Compiling derive_more-impl v1.0.0-beta.6
   Compiling backtrace-ext v0.2.1
   Compiling knuffel-derive v3.2.0 (https://github.com/TheLostLambda/knuffel.git#744bf56c)
   Compiling miette v7.2.0 (https://github.com/TheLostLambda/miette#5b3eeba9)
   Compiling nom-miette v0.1.0 (/home/neil/work/git/hub/Mesnage-Org/pgfinder/smithereens/crates/nom-miette)
   Compiling knuffel v3.2.0 (https://github.com/TheLostLambda/knuffel.git#744bf56c)
   Compiling derive_more v1.0.0-beta.6
   Compiling polychem v0.1.0 (/home/neil/work/git/hub/Mesnage-Org/pgfinder/smithereens/crates/polychem)
error[E0432]: unresolved import `std::num::NonZero`
 --> crates/polychem/src/atoms/atomic_database.rs:2:11
  |
2 | use std::{num::NonZero, ops::Deref, str::FromStr};
  |           ^^^^^-------
  |           |    |
  |           |    help: a similar name exists in the module: `NonZeroI8`
  |           no `NonZero` in `num`

error[E0432]: unresolved import `std::num::NonZero`
 --> crates/polychem/src/atoms/count.rs:3:5
  |
3 |     num::NonZero,
  |     ^^^^^-------
  |     |    |
  |     |    help: a similar name exists in the module: `NonZeroI8`
  |     no `NonZero` in `num`

error[E0432]: unresolved import `std::num::NonZero`
 --> crates/polychem/src/atoms/mass_number.rs:1:5
  |
1 | use std::num::NonZero;
  |     ^^^^^^^^^^-------
  |     |         |
  |     |         help: a similar name exists in the module: `NonZeroI8`
  |     no `NonZero` in `num`

error[E0432]: unresolved import `std::num::NonZero`
  --> crates/polychem/src/lib.rs:10:5
   |
10 | use std::num::NonZero;
   |     ^^^^^^^^^^-------
   |     |         |
   |     |         help: a similar name exists in the module: `NonZeroI8`
   |     no `NonZero` in `num`

error[E0658]: associated type bounds are unstable
  --> crates/polychem/src/atoms/errors.rs:74:56
   |
74 |     pub(crate) fn display_vec(items: impl IntoIterator<Item: Display>) -> String {
   |                                                        ^^^^^^^^^^^^^
   |
   = note: see issue #52662 <https://github.com/rust-lang/rust/issues/52662> for more information

error[E0658]: associated type bounds are unstable
   --> crates/polychem/src/polymers/errors.rs:220:44
    |
220 | pub fn comma_list(items: impl IntoIterator<Item: Display>, final_sep: &str) -> String {
    |                                            ^^^^^^^^^^^^^
    |
    = note: see issue #52662 <https://github.com/rust-lang/rust/issues/52662> for more information

error[E0658]: associated type bounds are unstable
   --> crates/polychem/src/polymers/polymer.rs:146:37
    |
146 |         residues: impl IntoIterator<Item: AsRef<str>>,
    |                                     ^^^^^^^^^^^^^^^^
    |
    = note: see issue #52662 <https://github.com/rust-lang/rust/issues/52662> for more information

error[E0658]: associated type bounds are unstable
   --> crates/polychem/src/polymers/polymer.rs:199:37
    |
199 |         residues: impl IntoIterator<Item: Borrow<ResidueId>>,
    |                                     ^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: see issue #52662 <https://github.com/rust-lang/rust/issues/52662> for more information

error[E0658]: associated type bounds are unstable
   --> crates/polychem/src/polymers/polymer.rs:346:35
    |
346 |         groups: impl IntoIterator<Item: Borrow<FunctionalGroup<'p>>> + Copy,
    |                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: see issue #52662 <https://github.com/rust-lang/rust/issues/52662> for more information

error[E0658]: associated type bounds are unstable
   --> crates/polychem/src/polymers/polymerizer_state.rs:118:35
    |
118 |         groups: impl IntoIterator<Item: Borrow<FunctionalGroup<'p>>>,
    |                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: see issue #52662 <https://github.com/rust-lang/rust/issues/52662> for more information

Some errors have detailed explanations: E0432, E0658.
For more information about an error, try `rustc --explain E0432`.
error: could not compile `polychem` (lib) due to 10 previous errors
```

## Building the Package for Web Assembly

I found the following...

>
> `wasm-pack` can then be used to build the `wasm-shim` package / crate which contains the code needed to run `smithereens` from the WebUI:
>
> ``` bash
> cd crates/wasm-shim/
> wasm-pack build --out-name smithereens --target web
> ```

...didn't work as on a fresh clone of the sub-module there is no such crate (`crates/wasm-shim/`) on the `main` branch, rather this currently resides on the `pgfinder-2` branch (although I expect it will make its way into `main` once you've finished work on it).


> `wasm-pack` can then be used to build the `wasm-shim` package / crate which contains the code needed to run `smithereens` from the WebUI. This is currently on the `pgfinder-2` branch:
> 
> ``` bash
> git switch pgfinder-2
> cd crates/wasm-shim/
> wasm-pack build --out-name smithereens --target web
> ```

Unfortunately that failed to build for me...

```bash
❱ wasm-pack build --out-name smithereens --target web
[INFO]: Checking for the Wasm target...
[INFO]: Compiling to Wasm...
   Compiling proc-macro2 v1.0.86
   Compiling unicode-ident v1.0.12
   Compiling wasm-bindgen-shared v0.2.92
   Compiling version_check v0.9.4
   Compiling log v0.4.22
   Compiling once_cell v1.19.0
   Compiling bumpalo v3.16.0
   Compiling wasm-bindgen v0.2.92
   Compiling cfg-if v1.0.0
   Compiling zerocopy v0.7.35
   Compiling thiserror v1.0.63
   Compiling syn v1.0.109
   Compiling autocfg v1.3.0
   Compiling allocator-api2 v0.2.18
   Compiling unicode-segmentation v1.11.0
   Compiling unicode-width v0.1.13
   Compiling serde v1.0.204
   Compiling unicode-xid v0.2.4
   Compiling minimal-lexical v0.2.1
   Compiling memchr v2.7.4
   Compiling rust_decimal v1.35.0
   Compiling heck v0.5.0
   Compiling base64 v0.22.1
   Compiling either v1.13.0
   Compiling ahash v0.8.11
   Compiling proc-macro-error-attr v1.0.4
   Compiling proc-macro-error v1.0.4
   Compiling arrayvec v0.7.4
   Compiling convert_case v0.6.0
   Compiling num-traits v0.2.19
   Compiling static_assertions v1.1.0
   Compiling itertools v0.13.0
   Compiling nom v7.1.3
   Compiling quote v1.0.36
   Compiling syn v2.0.72
   Compiling wasm-bindgen-backend v0.2.92
   Compiling knuffel-derive v3.2.0 (https://github.com/TheLostLambda/knuffel.git#744bf56c)
   Compiling thiserror-impl v1.0.63
   Compiling miette-derive v7.2.0 (https://github.com/TheLostLambda/miette#5b3eeba9)
   Compiling serde_derive v1.0.204
   Compiling derive_more-impl v1.0.0-beta.6
   Compiling wasm-bindgen-macro-support v0.2.92
   Compiling wasm-bindgen-macro v0.2.92
   Compiling miette v7.2.0 (https://github.com/TheLostLambda/miette#5b3eeba9)
   Compiling js-sys v0.3.69
   Compiling console_error_panic_hook v0.1.7
   Compiling derive_more v1.0.0-beta.6
   Compiling getrandom v0.2.15
   Compiling hashbrown v0.14.5
   Compiling nom-miette v0.1.0 (/home/neil/work/git/hub/Mesnage-Org/pgfinder/smithereens/crates/nom-miette)
   Compiling chumsky v0.9.3
   Compiling knuffel v3.2.0 (https://github.com/TheLostLambda/knuffel.git#744bf56c)
   Compiling polychem v0.1.0 (/home/neil/work/git/hub/Mesnage-Org/pgfinder/smithereens/crates/polychem)
error[E0432]: unresolved import `std::num::NonZero`
 --> crates/polychem/src/atoms/atomic_database.rs:2:11
  |
2 | use std::{num::NonZero, ops::Deref, str::FromStr};
  |           ^^^^^-------
  |           |    |
  |           |    help: a similar name exists in the module: `NonZeroI8`
  |           no `NonZero` in `num`

error[E0432]: unresolved import `std::num::NonZero`
 --> crates/polychem/src/atoms/count.rs:3:5
  |
3 |     num::NonZero,
  |     ^^^^^-------
  |     |    |
  |     |    help: a similar name exists in the module: `NonZeroI8`
  |     no `NonZero` in `num`

error[E0432]: unresolved import `std::num::NonZero`
 --> crates/polychem/src/atoms/mass_number.rs:1:5
  |
1 | use std::num::NonZero;
  |     ^^^^^^^^^^-------
  |     |         |
  |     |         help: a similar name exists in the module: `NonZeroI8`
  |     no `NonZero` in `num`

error[E0432]: unresolved import `std::num::NonZero`
  --> crates/polychem/src/lib.rs:10:5
   |
10 | use std::num::NonZero;
   |     ^^^^^^^^^^-------
   |     |         |
   |     |         help: a similar name exists in the module: `NonZeroI8`
   |     no `NonZero` in `num`

error[E0658]: associated type bounds are unstable
  --> crates/polychem/src/atoms/errors.rs:74:56
   |
74 |     pub(crate) fn display_vec(items: impl IntoIterator<Item: Display>) -> String {
   |                                                        ^^^^^^^^^^^^^
   |
   = note: see issue #52662 <https://github.com/rust-lang/rust/issues/52662> for more information

error[E0658]: associated type bounds are unstable
   --> crates/polychem/src/polymers/errors.rs:220:44
    |
220 | pub fn comma_list(items: impl IntoIterator<Item: Display>, final_sep: &str) -> String {
    |                                            ^^^^^^^^^^^^^
    |
    = note: see issue #52662 <https://github.com/rust-lang/rust/issues/52662> for more information

error[E0658]: associated type bounds are unstable
   --> crates/polychem/src/polymers/polymer.rs:146:37
    |
146 |         residues: impl IntoIterator<Item: AsRef<str>>,
    |                                     ^^^^^^^^^^^^^^^^
    |
    = note: see issue #52662 <https://github.com/rust-lang/rust/issues/52662> for more information

error[E0658]: associated type bounds are unstable
   --> crates/polychem/src/polymers/polymer.rs:199:37
    |
199 |         residues: impl IntoIterator<Item: Borrow<ResidueId>>,
    |                                     ^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: see issue #52662 <https://github.com/rust-lang/rust/issues/52662> for more information

error[E0658]: associated type bounds are unstable
   --> crates/polychem/src/polymers/polymer.rs:346:35
    |
346 |         groups: impl IntoIterator<Item: Borrow<FunctionalGroup<'p>>> + Copy,
    |                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: see issue #52662 <https://github.com/rust-lang/rust/issues/52662> for more information

error[E0658]: associated type bounds are unstable
   --> crates/polychem/src/polymers/polymerizer_state.rs:118:35
    |
118 |         groups: impl IntoIterator<Item: Borrow<FunctionalGroup<'p>>>,
    |                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: see issue #52662 <https://github.com/rust-lang/rust/issues/52662> for more information

Some errors have detailed explanations: E0432, E0658.
For more information about an error, try `rustc --explain E0432`.
error: could not compile `polychem` (lib) due to 10 previous errors
Error: Compiling your crate to WebAssembly failed
Caused by: Compiling your crate to WebAssembly failed
Caused by: failed to execute `cargo build`: exited with exit status: 101
  full command: cd "/home/neil/work/git/hub/Mesnage-Org/pgfinder/smithereens/crates/wasm-shim" && "cargo" "build" "--lib" "--release" "--target" "wasm32-unknown-unknown"
```

**Comment by TheLostLambda** [comment]
Hi @ns-rse !

The submodule should be initialised to the correct branch, but both of those issues look like a Rust version one!

Can you try with the latest stable release?  That's a new std library feature from the last release (or maybe one before) that I've used!

**Comment by ns-rse** [comment]
Hmm, seems I have a `rustc` under `$HOME/.cargo/bin/rustc` that may be getting in the way, will have a go at removing that and using the system version of `rust-1.79.0`.

Submodule definitely didn't initialise to the correct branch.

**Comment by TheLostLambda** [comment]
> Submodule definitely didn't initialise to the correct branch.

Eek! I'll investigate...

**Comment by TheLostLambda** [comment]
> Submodule definitely didn't initialise to the correct branch.

Testing a fresh clone, after initializing the submodule, I've ended up with: `HEAD detached at 0a5f7fa`, which does seem to have the `wasm-shim` directory!

Once we merge this PR, then I think cloning with `git clone --recurse-submodules` should work too!

**Comment by ns-rse** [comment]
Updated `rustup` to `1.79.0` and `smithereens` all builds under native and the `wasm-shim` builds using `wasm-pack`. :+1: :tada: 

Updated documentation to reflect this minimum version.

WebUI throws a hissy fit though...

```
[plugin:vite:import-analysis] Failed to resolve import "client-zip" from "src/lib/smithereens.ts?type=module&worker_file". Does the file exist?
/home/neil/work/git/hub/Mesnage-Org/pgfinder/web/src/lib/smithereens.ts:6:28
1  |  import "/@vite/env"
2  |  import { downloadZip } from "client-zip";
   |                               ^
3  |  import init, { Peptidoglycan, version } from "smithereens";
4  |  (async () => {
    at formatError (file:///home/neil/work/git/hub/Mesnage-Org/pgfinder/web/node_modules/.pnpm/vite@4.5.2_@types+node@20.5.9/node_modules/vite/dist/node/chunks/dep-52909643.js:44062:46)
    at TransformContext.error (file:///home/neil/work/git/hub/Mesnage-Org/pgfinder/web/node_modules/.pnpm/vite@4.5.2_@types+node@20.5.9/node_modules/vite/dist/node/chunks/dep-52909643.js:44058:19)
    at normalizeUrl (file:///home/neil/work/git/hub/Mesnage-Org/pgfinder/web/node_modules/.pnpm/vite@4.5.2_@types+node@20.5.9/node_modules/vite/dist/node/chunks/dep-52909643.js:41844:33)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///home/neil/work/git/hub/Mesnage-Org/pgfinder/web/node_modules/.pnpm/vite@4.5.2_@types+node@20.5.9/node_modules/vite/dist/node/chunks/dep-52909643.js:41998:47
    at async Promise.all (index 1)
    at async TransformContext.transform (file:///home/neil/work/git/hub/Mesnage-Org/pgfinder/web/node_modules/.pnpm/vite@4.5.2_@types+node@20.5.9/node_modules/vite/dist/node/chunks/dep-52909643.js:41914:13)
    at async Object.transform (file:///home/neil/work/git/hub/Mesnage-Org/pgfinder/web/node_modules/.pnpm/vite@4.5.2_@types+node@20.5.9/node_modules/vite/dist/node/chunks/dep-52909643.js:44352:30)
    at async loadAndTransform (file:///home/neil/work/git/hub/Mesnage-Org/pgfinder/web/node_modules/.pnpm/vite@4.5.2_@types+node@20.5.9/node_modules/vite/dist/node/chunks/dep-52909643.js:55026:29)
    at async viteTransformMiddleware (file:///home/neil/work/git/hub/Mesnage-Org/pgfinder/web/node_modules/.pnpm/vite@4.5.2_@types+node@20.5.9/node_modules/vite/dist/node/chunks/dep-52909643.js:64430:32
Click outside, press Esc key, or fix the code to dismiss.
You can also disable this overlay by setting server.hmr.overlay to false in vite.config.js.
```

I can see `client-zip` is listed in the `package.json` so updated with `pnpm install` and all was back to normal :relieved: the Svelte side of things will need documenting at some point too.

**Comment by TheLostLambda** [comment]
Nice! Yeah, it's a new dependency, so needing the install makes sense!

Do you mean usage docs or developer docs for the Svelte stuff?

**Comment by ns-rse** [comment]
> Do you mean usage docs or developer docs for the Svelte stuff?

The later, developer docs for Svelte. It would be useful to help people new to the framework to get up and running.

**Comment by TheLostLambda** [comment]
@ns-rse Fixed that CI-failing-one-Windows issue: https://github.com/mesonbuild/meson-python/issues/559

All of the other lints and checks should be passing now too!

Missing things to do before merging:

- [ ] Add Usage documentation

And to convert to issues:

- [ ] Add Svelte developer documentation
- [ ] Write tests for the new UI modules

**Comment by TheLostLambda** [comment]
@ns-rse Might need your help in understanding some of how the documentation is generated here?

I'm utterly baffled by these image links — where to get the URLs and how to upload new images:
``` md
![Initial screenshot of PGFinder GUI](https://github.com/Mesnage-Org/pgfinder/assets/70374280/9537c200-5b48-4d50-ac72-1c8b62d83909)
```

**Comment by TheLostLambda** [comment]
In the meantime I'll be going back to things in the `img/` directory: 
image

I've heard that might mean that the images don't load on GitHub, but at least that's straightforward!

**Comment by TheLostLambda** [comment]
Going to merge things just so that we can make sure the documentation and everything is set up, public, and working for publishing the paper!

I hate to rush this bit through, but I think I've added issues for dealing with any loose-ends left behind!

Some bigger issues (but bike-sheddy ones) that we need to think about involve the versioning and naming (and changelog tracking) for essentially three separate bits of software: the CLI PGfinder, the WebUI, and the new Smithereens stuff.

**Pull request merged**
