### PR TITLE
8 | Replaced all print/logging statements with logging using pgfinder…

### LINKED ISSUE #8: Replace print statements with logging
Allows control of how much stuff is output under what circumstances and helps with running remotely. Basically replace `print` with `logger.info`.

### PR DESCRIPTION
**Pull request by ns-rse**
Resolves #8 

I replaced some of the `print()` statements in #75, this replaces the remainder but is contingent on #75 being merged first since it introduces the `pgfinder.logs.logs` sub-module that sets up the logger. 

Apologies for conflating two issues across two PRs, will endeavour to keep things more focused and on topic in subsequent branches/PRs.

### CODE REVIEW

**Comment by ns-rse** [comment]
By the way, if anyone thinks this should just be rolled into #75 please let me know and I will do so.

**Comment by ns-rse** [comment]
Just to say almost all of the issues Codacy reports are a consequence of having applied Black formatting to the data as it has replaced `'` with `"`. Much of these will be addressed when by parameterisation of variables which is in the pipeline.

**Comment by bobturneruk** [comment]
Codacy is advisory, but we can tune it to better meet this project's needs.

**Comment by bobturneruk** [comment]
I was sure I'd approved this! I'll have another quick look.

**Review by bobturneruk — APPROVED** [review]
Looks good.

**Review by Ankur-AVP-Patel — APPROVED** [review]

**Comment by ns-rse** [comment]
Thanks both for the approvals & the merge @Ankur-AVP-Patel hopefully it unblocks the way for your PR.

**Pull request merged**
