### PR TITLE
fix!: don't round abundance

### LINKED ISSUE #274: Consolidation issue
Abundance value needs more decimals (currently 2), otherwise consolidation across samples leads to intensities = zero
See average tab, highlighted lines in file attached.
[Cross sample consolidation example.xlsx](https://github.com/Mesnage-Org/pgfinder/files/14648909/Cross.sample.consolidation.example.xlsx)

### PR DESCRIPTION
**Pull request by TheLostLambda**
Closes #274

### CODE REVIEW

**Review by ns-rse — COMMENTED** [review]
Simple fix, I wonder though, with my mind in the parameterisation state, whether we should set significant digits to be an option to functions that is configurable (both via a default configuration file and via the WebUI)?

Something to consider for subsequent work.

**Comment by TheLostLambda** [comment]
@ns-rse Don't know how this ended up as a draft PR the first time, but things are ready to merge now!

Then I just need to remember to make that changelog and 1.2.0 release!

**Review by ns-rse — APPROVED** [review]
Will four decimal places for the percentages and other numbers be sufficient?

I often think its better to give people really precise numbers and let them then round up as they see fit rather than having to go round in circles giving greater precision each time its requested (ties in with making it configurable).

Aside from that question, good to go.

**Comment by TheLostLambda** [comment]
@ns-rse I asked the same of @smesnage , if we should just not round anything (so there is never information lost) but he seems keen on keeping the 1 digit for ppm and two for retention time at the moment. It's probably a nice thing to put in any issue regarding the rounding.

I think the "best solution" would be being able to pick between CSV of Excel output — then we could apply formatting (like visual rounding, but behind the scenes all digits are kept) to these columns, and the CSV could remain all raw, unrounded data.

But that's a lot of code changes to be made, and it probably lower priority than the integration of the fragmenter / mass-calc via WASM (as I understand)!

**Pull request merged**
