### PR TITLE
Switching to RTD theme

### PR DESCRIPTION
**Pull request by ns-rse**
In an attempt to get multiple versions of docs built on ReadTheDocs I've switched themes to the RTD theme. At the same time I noticed the automatic building of API documentation was not happening so I've (hopefully) rendered that and it will be available across all versions going forward.

Not yet sure whether the "[flyout](https://docs.readthedocs.io/en/stable/flyout-menu.html)" menu will be rendered, its not shown locally and a [thread](https://stackoverflow.com/questions/66436744/how-to-activate-the-rtd-flyout-menu) referenced problems in the past and there are some issues on GitHub but these appear to have been resolved.

### CODE REVIEW

**Comment by ns-rse** [comment]
I had some merge conflicts with this PR as a result of #227 being merged.

Resolved them locally but now tests fail because of a missing  `pgfinder/pgfinder/masses` I have a `lib/pgfinder/masses/` directory in this branch but its empty.

Not familiar with Playwright testing frame work (nor Svelte!) any thoughts/advice welcome @TheLostLambda

**Comment by TheLostLambda** [comment]
Sorry for breaking things! I'll take a look!

**Comment by TheLostLambda** [comment]
@ns-rse Not your fault at all! The playwright testing has a test that checks all of the links on the website are live and go where they should! One of those links points to the master branch folder that should contain the mass libraries, but that folder was moved after I merged my PR!

I'll merge this in, then fix that test with another PR in a moment! This PR doesn't break the code — it's already broken!

**Review by TheLostLambda — APPROVED** [review]

**Comment by ns-rse** [comment]
Brilliant, thanks @TheLostLambda

**Pull request merged**
