### PR TITLE
Add content needed for JOSS submission

### PR DESCRIPTION
**Pull request by bobturneruk**
Resolves https://github.com/Mesnage-Org/pgfinder/issues/109

### CODE REVIEW

**Comment by bobturneruk** [comment]
Progress (kind of) depends on #109 and probably we also need a new release before submission.

**Comment by TheLostLambda** [comment]
Boo! It's the aforementioned ghost of JOSS! Steph and I were thinking that I'd try to help push this over the line and we can talk about the major improvements that have been made to the codebase, interface, and functionality since the original paper!

It looks like you've already made quite a lot of progress on things, so it might be nice to have a meeting at some point to catch up with where exactly things stand!

**Comment by ns-rse** [comment]
Sure lets see when @bobturneruk and everyone is free, my calendar is fairly up-to-date.

**Comment by smesnage** [comment]
I did quite a bit of re-writing in the google doc that Bob sent. Please have a look and amend if needed.

**Comment by TheLostLambda** [comment]
Final time for @ns-rse and @bobturneruk to check! I plan to press the button tomorrow!

**Comment by smesnage** [comment]
THis can go, right?

**Comment by TheLostLambda** [comment]
Technically yes, though we **can not** delete this branch, or all of the JOSS work disappears!

I might reopen this pull request for the time being, just it make it slightly harder to accidentally delete all of the JOSS work :sweat_smile:

**Comment by TheLostLambda** [comment]
Well, we probably still shouldn't delete the branch, but I think that a JOSS rejection means we can probably close this pull request...

**Pull request closed without merging**
