### PR TITLE
Re-write of docs/usage.md

### LINKED ISSUE #180: Revise docs/usage.md
The `docs/usage.md` page needs considerable revision to reflect usage of the WebUI.

This should include...

* Screenshots of WebUI
* Rounding out of how to create/use a YAML configuration file for use at the Command Line (@ns-rse).

### PR DESCRIPTION
**Pull request by ns-rse**
Closes #180

Re-writes the `docs/usage` page of the website with description and screenshots for using [mesnage-org.github.io/pgfinder-gui](https://mesnage-org.github.io/pgfinder-gui/).

### CODE REVIEW

**Comment by smesnage** [comment]
Do you have the equivalent document for the original myBinder?
I can give it a shot once I know what you're after, especially how much details are needed.
Sorry you have to tell me everyting!

**Comment by TheLostLambda** [comment]
On a quick glance, this looks great! I'll take a closer look in the next few days!

**Comment by ns-rse** [comment]
> Do you have the equivalent document for the original myBinder?
> I can give it a shot once I know what you're after, especially how much details are needed.

The current documentation has the JupyterLite version which really just replaced the screenshots so they aligned, see [here](https://mesnage-org.github.io/pgfinder/master/usage.html).

You can see a crude example of how it renders in HTML [here](https://github.com/Mesnage-Org/pgfinder/blob/ns-rse/180-revise-usage.md/docs/usage.md) which includes the text and in-line images.

> Sorry you have to tell me everything!

Not a problem at all, its really useful to have your feedback.

> On a quick glance, this looks great! I'll take a closer look in the next few days!

Cool, no rush, just had some time where I need something relaitvely mindless to do so figured I'd go through, take some screenshots and have a go at re-writing the text. Feedback welcome. :smile:

**Comment by TheLostLambda** [comment]
Still needs an even deeper look, but I don't know if any of the cache-clearing stuff is still valid. Pyodide doesn't actually seem to cache anything by default — I think that was JupyterLite playing intentionally with IndexedDB. I'm thinking about adding the cache back, but with an explicit check / hash of the pip package info so it's invalidated every time PGFinder is updated!

**Comment by ns-rse** [comment]
> Still needs an even deeper look, but I don't know if any of the cache-clearing stuff is still valid. Pyodide doesn't actually seem to cache anything by default — I think that was JupyterLite playing intentionally with IndexedDB. 

Checked https://mesnage-org.github.io/pgfinder-gui/ from Firefox, Opera and Chromium

+ Firefox says there isn't anything being stored by the site.
+ Opera not clear, but takes a while to load mass libraries and options suggesting they're not cached.
+ Chromium not clear, but again takes a while to load mass libraries and options suggesting they're not cached.

I found [this thread](https://github.com/pyodide/pyodide/issues/3940) which points to [this article on WASM caching](https://v8.dev/blog/wasm-code-caching) but my (crude) understanding is that caching WASM wouldn't be a problem.


> I'm thinking about adding the cache back, but with an explicit check / hash of the pip package info so it's invalidated every time PGFinder is updated!

That would be neat, although I think a more general solution would be if we could include the ability in `pgfinder-gui` for users to select what version they run against if that is at all possible. An issue for a different repo perhaps, not sure if we should aim to include it prior to submission of JOSS (can always keep adding things!).

**Comment by ns-rse** [comment]
Removed reference to clearing cache, if no other comments or tweaks this is ready to merge.

**Comment by TheLostLambda** [comment]
I think it looks great! Only thing is that a couple of GUI tweaks in the
next few days might warrant new screenshots, but those can be a second PR
if you'd prefer!

**Comment by ns-rse** [comment]
> I think it looks great! Only thing is that a couple of GUI tweaks in the next few days might warrant new screenshots, but those can be a second PR if you'd prefer!

Great, I'll merge this, we can tweak in the future. Not a fan of PRs dragging out, counter to the idea that commits should be small.

**Pull request merged**
