### PR TITLE
Improve docs

### PR DESCRIPTION
**Pull request by bobturneruk**
Whhy am I using the branch again! It's not a big problem, I suppose, but not great practise!

Anyway - the idea of this is to make some improvements to the docs prior to a JOSS submission. Also relates to #144 in that it changes the data dictionary, which probably needs to be updated as per #114.

### CODE REVIEW

**Review by ns-rse — APPROVED** [review]
Looks good, one missing `many`.

When I substitute `versioneer` for `setuptools_scm` I will make sure I update the documentation.

**Comment by ns-rse** [comment]
Bah, I clicked on a link that only showed the changes to the first few commits, can't revoke approvals and its still a work in progress. Sorry :crying_cat_face:

**Comment by bobturneruk** [comment]
Thanks for having a 👀 @ns-rse.

**Comment by bobturneruk** [comment]
This is ready to go, but the data dictionary will need an update soon.

**Review by ns-rse — APPROVED** [review]
Thanks for bulking all this out @bobturneruk looks good to merge.

**Pull request merged**
