### PR TITLE
Remove sphinx.ext.autosummary from lib/docs/conf.py

### LINKED ISSUE #239: API Documentation Seems Non-Existant on ReadTheDocs
Probably one for our documentation wizards @ns-rse and @bobturneruk — for some reason or another, it looks like none of the docstrings are being built into documentation?

All empty in the `pgfinder` module here: https://pgfinder.readthedocs.io/en/latest/api.html

### PR DESCRIPTION
**Pull request by ns-rse**
Hopefully this closes #239 and the API duplication will no longer occur.

### CODE REVIEW

**Comment by ns-rse** [comment]
Hmm, I think I may have been distracted and failed to put out a PR to remove the duplicate API. End-to-end tests are failing, so I merged `origin/main` into this branch as I recall you saying it was something you would fix @TheLostLambda but I think that may still be pending?

**Comment by TheLostLambda** [comment]
@ns-rse I'll try to sort out what the CI testing is upset about. In the meantime, can we delete `lib/docs/api.rst`?

**Comment by ns-rse** [comment]
@TheLostLambda thanks, wasn't paying attention, now removed.

**Comment by TheLostLambda** [comment]
Let's hope this helps!

**Comment by ns-rse** [comment]
:+1: What is the difference between `pnpm` and `pnpx`?

(I know little to nothing about these frameworks!).

**Comment by TheLostLambda** [comment]
The normal JS package manager is `pnpm` (and it allows you to run programs installed locally in the `node_modules` folder), and `pnpx` is a version that executes a remote package as a command. It installs the latest version on the fly, then runs the program.

The issue with the CI tests was that a new version of Playwright was released, so `pnpx` started pulling that new version, and it installed versions of the test browsers that were incompatible with the version of Playwright in our `package.json`. It looks like, by changing out `pnpx` for `pnpm exec`, you can run the locally installed `playwright` that respects the semantic versioning requirements set in the `package.json`.

That's how I came to understand things, anyways! Half of the CI process was using a newer version of Playwright that had been released, but the testing phase (`pnpm test`) used our older, locked version, so things broke.

**Pull request merged**
