### PR TITLE
Moving config so binder picks it up

### LINKED ISSUE #142: myBinder Crashes
image

@ns-rse - I feel like I've seen this before.

@smesnage reported this - any more details on what you were doing?

### PR DESCRIPTION
**Pull request by ns-rse**
This appears to resolve #142 although it takes a while to upload the `.ftrs` file and so after having selected the file to upload you _must_ now wait for the file to be listed next to the "Upload Deconvoluted Data" button as highlighted below...

binder_upload

### CODE REVIEW

**Comment by TheLostLambda** [comment]
Great work tracking this down, @ns-rse ! It looks like it's definitely and issue that others have had and the same / similar solution (https://discourse.jupyter.org/t/binder-configuration-for-large-ipywidget-file-upload/4662/4), so I think it should be pretty safe to merge this!

At some point it could still be interesting to look into JupyterLite (I think doing that all in WASM on the client side is a nice way to free us from needed a server like Colab or Binder), but I think merging this ASAP so that people can use the Binder version of PGFinder is top priority at the moment!

**Review by TheLostLambda — APPROVED** [review]

**Comment by TheLostLambda** [comment]
Oh, and for what it's worth, I've experienced that upload delay before! It was most obvious after I added the bit that displays filenames (since they took a while to pop up!) I don't think that's something particularly new to this version of the code!

Merge things whenever you'd like! If @smesnage needs to use things today, I can try merging too — I think the CI is set up to autodeploy from master?

**Comment by ns-rse** [comment]
Thanks @TheLostLambda for the prompt review and for tracking down similar issues.

One of the issues with Binder that may be contributing to this  is that they have just lost a considerable amount of resources (see [blog post](https://blog.jupyter.org/mybinder-org-reducing-capacity-c93ccfc6413f)) and so this may be why it now takes longer for uploads to occur.

To which end I would _really_ like to get things working with JupyterLite though as that would definitely free us from this restriction/bottleneck.  Currently there are two issues though...

1. Can't (easily, if at all) install `pgfinder` from GitHub as there is no easily accessible storage to `git clone` the repository to (something `pip install git+<repo_url>` does in the background)
2. Current release on PyPI has a dependency on `pysqlite3` for which there are now "wheels" (`.whl`) releases and so it JupyterLite can't build the package from source.

The later problem should be addressable with a new release as it looks like we've removed that dependency but I would still like to solve the former so that new features can be easily tested.

In the mean time though you are absolutely right, getting this merged and simply waiting for the uploads of `.ftrs` to complete is paramount. I've just added some extra details to the documentation about the need to wait for uploads to complete so that is documented for now (hopefully once we get a working JupyterLite solution working we can remove the dependency on Binder).

**Comment by TheLostLambda** [comment]
Sounds like a good way forward! I'll leave this (something you've probably already seen) as a sort of note to myself that could be helpful here!

https://github.com/jupyterlite/demo

**Pull request merged**
