### PR TITLE
Update formatting and links

### PR DESCRIPTION
**Pull request by bobturneruk**
If this works it will be followed by a PR to remove the GH Action to build docs.

### CODE REVIEW

**Comment by TheLostLambda** [comment]
Outstanding work so far! The docs on RTD look great!

**Review by TheLostLambda — APPROVED** [review]
Whoops! Forgot to actually review things!

Looks great, but there might be a link or two left behind?
image

After those are tidied, good to merge!

**Comment by TheLostLambda** [comment]
> If this works it will be followed by a PR to remove the GH Action to build docs.

Is this something that still needs to be done?

**Comment by bobturneruk** [comment]
Yes. You're welcome to jump in and do it. The settings for pages should be turned off temporarily, too.

**Pull request merged**
